# This is a basic workflow to help you get started with Actions

name: mac

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          brew update
          brew install boost 
          brew install cmake

      - name: Install deps
        run: |
          python -m pip install cibuildwheel==2.3.1
          python -m pip install -r ./dev-requirements.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: ls wheelhouse/

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

#      - name: Deploy Test PyPI
#        if: startsWith(github.ref, 'refs/tags') != true
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          password: ${{ secrets.test_pypi_token }}
#          repository_url: https://test.pypi.org/legacy/
